# Generated by Django 2.2.1 on 2019-05-10 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='作者姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='作者联系邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章标题')),
                ('tagline', models.TextField(verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, verbose_name='内容摘要')),
                ('body_text', models.TextField(verbose_name='文章内容')),
                ('pub_date', models.DateField(verbose_name='创建日期')),
                ('mod_date', models.DateField(verbose_name='修改日期')),
                ('n_comments', models.IntegerField(verbose_name='评论数量')),
                ('n_pingbacks', models.IntegerField(verbose_name='阅读量')),
                ('auther', models.ManyToManyField(to='pages.Auther')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Blog')),
            ],
        ),
    ]
